//! Calendar 资源模块

pub mod acl;
/// event 模块。
pub mod event;
/// models 模块。
pub mod models;

/// create 模块。
pub mod create;
/// delete 模块。
pub mod delete;
/// get 模块。
pub mod get;
/// list 模块。
pub mod list;
/// mget 模块。
pub mod mget;
/// patch 模块。
pub mod patch;
/// primary 模块。
pub mod primary;
/// primarys 模块。
pub mod primarys;
/// search 模块。
pub mod search;
/// subscribe 模块。
pub mod subscribe;
/// subscription 模块。
pub mod subscription;
/// unsubscribe 模块。
pub mod unsubscribe;
/// unsubscription 模块。
pub mod unsubscription;
