use super::super::DefaultServiceRegistry;
use crate::Result;

compiled_services! {
    {
        feature: "auth",
        name: "auth",
        description: "飞书认证服务，提供令牌管理、身份验证等功能",
        dependencies: [],
        provides: ["token-management", "permission-control"],
        priority: 1,
    },
    {
        feature: "communication",
        name: "communication",
        description: "飞书通讯服务，提供消息、联系人、群组等功能",
        dependencies: ["auth"],
        provides: ["im", "contacts", "groups"],
        priority: 2,
    },
    {
        feature: "docs",
        name: "docs",
        description: "飞书文档服务，提供云文档、表格、知识库等功能",
        dependencies: ["auth"],
        provides: ["cloud-docs", "sheets", "wiki"],
        priority: 2,
    },
    {
        feature: "cardkit",
        name: "cardkit",
        description: "飞书卡片服务，提供卡片渲染与交互能力",
        dependencies: ["auth"],
        provides: ["card"],
        priority: 3,
    },
    {
        feature: "meeting",
        name: "meeting",
        description: "飞书会议服务，提供视频会议与会议室管理能力",
        dependencies: ["auth"],
        provides: ["vc"],
        priority: 3,
    },
    {
        feature: "security",
        name: "security",
        description: "飞书安全服务，提供安全审计与风控相关能力",
        dependencies: ["auth"],
        provides: ["security"],
        priority: 3,
    },
    {
        feature: "hr",
        name: "hr",
        description: "飞书人力资源服务，提供员工、考勤、薪酬等功能",
        dependencies: ["auth"],
        provides: ["attendance", "corehr", "ehr"],
        priority: 4,
    },
    {
        feature: "ai",
        name: "ai",
        description: "飞书AI服务，提供智能助手、AI分析等功能",
        dependencies: ["auth", "communication"],
        provides: ["chatbot", "smart-analysis"],
        priority: 4,
    },
    {
        feature: "workflow",
        name: "workflow",
        description: "飞书工作流服务，提供审批、任务、看板等功能",
        dependencies: ["auth"],
        provides: ["approval", "task", "board"],
        priority: 4,
    },
    {
        feature: "platform",
        name: "platform",
        description: "飞书平台服务，提供应用平台相关功能",
        dependencies: ["auth"],
        provides: ["app-platform"],
        priority: 4,
    },
    {
        feature: "application",
        name: "application",
        description: "飞书应用服务，提供应用管理相关功能",
        dependencies: ["auth"],
        provides: ["app-management"],
        priority: 4,
    },
    {
        feature: "helpdesk",
        name: "helpdesk",
        description: "飞书帮助台服务，提供工单管理相关功能",
        dependencies: ["auth"],
        provides: ["ticket"],
        priority: 4,
    },
    {
        feature: "mail",
        name: "mail",
        description: "飞书邮件服务，提供邮件相关功能",
        dependencies: ["auth"],
        provides: ["email"],
        priority: 4,
    },
    {
        feature: "analytics",
        name: "analytics",
        description: "飞书分析服务，提供数据分析相关功能",
        dependencies: ["auth"],
        provides: ["report"],
        priority: 4,
    },
    {
        feature: "user",
        name: "user",
        description: "飞书用户服务，提供用户设置相关功能",
        dependencies: ["auth"],
        provides: ["settings"],
        priority: 4,
    },
}
